"""Static, hand-curated corporate-intelligence question bank.

40 questions, 8 per company, grounded in the reference newsroom notes
(current to 2025-2026 reporting). Correct answers are authored at index 0;
the API layer shuffles both option order and question order at serve time,
so each quiz restart presents a fresh arrangement.
"""

QUESTIONS = [
    # ---------------- ANZ ----------------
    {
        "id": "anz-1", "company": "ANZ", "category": "Market Position",
        "question": "ANZ is regarded as one of Australia's what?",
        "options": ["Big Four banks", "Big Three banks", "Big Five banks", "Big Six banks"],
        "correctIndex": 0,
        "explanation": "ANZ is one of Australia's 'Big Four' banks, alongside CBA, Westpac and NAB.",
    },
    {
        "id": "anz-2", "company": "ANZ", "category": "Market Position",
        "question": "Where does ANZ rank in Australia by market capitalisation and mortgage share?",
        "options": ["4th-largest", "1st-largest", "2nd-largest", "3rd-largest"],
        "correctIndex": 0,
        "explanation": "ANZ is the 4th-largest of the Big Four by market capitalisation and mortgage share.",
    },
    {
        "id": "anz-3", "company": "ANZ", "category": "Operations",
        "question": "Which of the following is NOT a core segment of ANZ's operations?",
        "options": ["Investment banking", "Retail banking", "Business banking", "New Zealand banking"],
        "correctIndex": 0,
        "explanation": "ANZ operates retail, business, institutional and New Zealand banking; pure investment banking is not a core segment.",
    },
    {
        "id": "anz-4", "company": "ANZ", "category": "Leadership",
        "question": "Who is the current CEO of ANZ?",
        "options": ["Nuno Matos", "Shayne Elliott", "Kevin Gallagher", "Bruce Mathieson Jr"],
        "correctIndex": 0,
        "explanation": "Nuno Matos is ANZ's CEO, having succeeded long-serving CEO Shayne Elliott.",
    },
    {
        "id": "anz-5", "company": "ANZ", "category": "Leadership",
        "question": "Who is the former CEO of ANZ who preceded Nuno Matos?",
        "options": ["Shayne Elliott", "Simon Trott", "Bruce Mathieson Jr", "Nuno Matos"],
        "correctIndex": 0,
        "explanation": "Shayne Elliott was ANZ's long-serving CEO before Nuno Matos took over.",
    },
    {
        "id": "anz-6", "company": "ANZ", "category": "M&A",
        "question": "In September 2026, ANZ reportedly held talks to acquire which SME lender (valued ~A$1.13bn)?",
        "options": ["Judo Bank", "Tyro Payments", "Latitude Financial", "Pepper Money"],
        "correctIndex": 0,
        "explanation": "ANZ reportedly held talks to acquire Judo Bank, an SME lender valued at about A$1.13 billion, to diversify away from mortgage lending.",
    },
    {
        "id": "anz-7", "company": "ANZ", "category": "Financials",
        "question": "What cash earnings did ANZ report for Q3 FY2025?",
        "options": ["A$1.9 billion", "A$1.5 billion", "A$1.7 billion", "A$2.1 billion"],
        "correctIndex": 0,
        "explanation": "ANZ reported A$1.9 billion in cash earnings for Q3 FY2025, with bad-debt charges well below forecasts.",
    },
    {
        "id": "anz-8", "company": "ANZ", "category": "Financials",
        "question": "What was ANZ's reported CET1 (Common Equity Tier 1) capital ratio?",
        "options": ["12.51%", "12.01%", "12.25%", "12.75%"],
        "correctIndex": 0,
        "explanation": "ANZ reported a CET1 capital ratio of 12.51%, with a net interest margin (NIM) of 1.54%.",
    },

    # ---------------- The Star Entertainment Group ----------------
    {
        "id": "star-1", "company": "Star", "category": "Market Position",
        "question": "What is The Star Entertainment Group's position in Australia's casino operator market?",
        "options": ["Second-largest", "Largest", "Third-largest", "Fourth-largest"],
        "correctIndex": 0,
        "explanation": "The Star is Australia's second-largest casino operator, behind Crown Resorts.",
    },
    {
        "id": "star-2", "company": "Star", "category": "Key Properties",
        "question": "Which of the following casinos is NOT operated by The Star Entertainment Group?",
        "options": ["Crown Melbourne", "The Star Sydney", "The Star Gold Coast", "Treasury Brisbane"],
        "correctIndex": 0,
        "explanation": "Star operates The Star Sydney, The Star Gold Coast and Treasury Brisbane; Crown Melbourne belongs to Crown Resorts.",
    },
    {
        "id": "star-3", "company": "Star", "category": "Regulatory Review",
        "question": "What initial fine was imposed on Star Sydney after the Bell Inquiry found serious failures?",
        "options": ["A$100 million", "A$10 million", "A$50 million", "A$200 million"],
        "correctIndex": 0,
        "explanation": "After the 2022 Bell Inquiry found serious AML, governance and compliance failures, Star Sydney lost its licence and was fined A$100 million.",
    },
    {
        "id": "star-4", "company": "Star", "category": "AML Enforcement",
        "question": "In which year did AUSTRAC launch civil proceedings against Star entities?",
        "options": ["2022", "2020", "2021", "2023"],
        "correctIndex": 0,
        "explanation": "Australia's financial-crime watchdog AUSTRAC launched civil proceedings against Star entities in 2022.",
    },
    {
        "id": "star-5", "company": "Star", "category": "Governance",
        "question": "What penalty did former Star CEO Matthias Bekier receive in June 2025?",
        "options": [
            "Banned from managing companies for 6 years and fined A$700,000",
            "Banned for 3 years and fined A$500,000",
            "Banned for 6 years and fined A$1 million",
            "Banned for 10 years and fined A$700,000",
        ],
        "correctIndex": 0,
        "explanation": "In June 2025 former CEO Matthias Bekier was banned from managing companies for 6 years and fined A$700,000.",
    },
    {
        "id": "star-6", "company": "Star", "category": "Restructuring",
        "question": "In March 2025, The Star secured a A$390 million loan from which partner?",
        "options": ["WhiteHawk Capital Partners", "BlackRock", "Carlyle Group", "Apollo Global Management"],
        "correctIndex": 0,
        "explanation": "In a March 2025 refinancing, Star secured a A$390 million loan from WhiteHawk Capital Partners.",
    },
    {
        "id": "star-7", "company": "Star", "category": "Ownership",
        "question": "Who is The Star Entertainment Group's largest shareholder?",
        "options": ["The Mathieson family", "The Chinese government", "A consortium of hedge funds", "A sovereign wealth fund"],
        "correctIndex": 0,
        "explanation": "The Mathieson family is Star's largest shareholder.",
    },
    {
        "id": "star-8", "company": "Star", "category": "Leadership",
        "question": "Who was appointed CEO of The Star Entertainment Group in December 2024?",
        "options": ["Bruce Mathieson Jr", "Matthias Bekier", "HC Charles Diao", "Simon Trott"],
        "correctIndex": 0,
        "explanation": "Bruce Mathieson Jr was appointed CEO of The Star in December 2024.",
    },

    # ---------------- Santos ----------------
    {
        "id": "santos-1", "company": "Santos", "category": "Market Position",
        "question": "What is Santos's position among Australia's independent oil & gas producers?",
        "options": ["Second-largest", "Largest", "Third-largest", "Fourth-largest"],
        "correctIndex": 0,
        "explanation": "Santos is Australia's second-largest independent oil & gas producer.",
    },
    {
        "id": "santos-2", "company": "Santos", "category": "Key Assets",
        "question": "Which of the following is NOT a key asset of Santos?",
        "options": ["Gorgon LNG", "Barossa", "Pikka (Alaska)", "PNG LNG"],
        "correctIndex": 0,
        "explanation": "Santos's key assets include Barossa, Pikka (Alaska), PNG LNG and Papua LNG; Gorgon LNG is operated by Chevron.",
    },
    {
        "id": "santos-3", "company": "Santos", "category": "Leadership",
        "question": "Who is the CEO & Managing Director of Santos?",
        "options": ["Kevin Gallagher", "Simon Trott", "Bruce Mathieson Jr", "Zubin Appoo"],
        "correctIndex": 0,
        "explanation": "Kevin Gallagher is Santos's CEO & Managing Director.",
    },
    {
        "id": "santos-4", "company": "Santos", "category": "Guidance",
        "question": "What is Santos's reiterated annual production guidance (million boe)?",
        "options": ["99-105 million boe", "90-100 million boe", "105-110 million boe", "110-115 million boe"],
        "correctIndex": 0,
        "explanation": "Santos reiterated annual production guidance of 99-105 million barrels of oil equivalent.",
    },
    {
        "id": "santos-5", "company": "Santos", "category": "Projects",
        "question": "When is Santos targeting a final investment decision (FID) for Papua LNG?",
        "options": ["End-2026", "End-2025", "End-2027", "End-2028"],
        "correctIndex": 0,
        "explanation": "Santos is targeting an FID on Papua LNG by end-2026; partners include TotalEnergies and ExxonMobil.",
    },
    {
        "id": "santos-6", "company": "Santos", "category": "Projects",
        "question": "Which companies are partners with Santos in the Papua LNG project?",
        "options": ["TotalEnergies and ExxonMobil", "Shell and Chevron", "BP and ConocoPhillips", "Equinor and Woodside"],
        "correctIndex": 0,
        "explanation": "TotalEnergies and ExxonMobil are Santos's partners in Papua LNG.",
    },
    {
        "id": "santos-7", "company": "Santos", "category": "Projects",
        "question": "What is the planned production capacity of Santos's Pikka project in Alaska?",
        "options": ["80,000 bpd", "23,000 bpd", "40,000 bpd", "100,000 bpd"],
        "correctIndex": 0,
        "explanation": "Pikka currently produces ~23,000 bpd and has a planned capacity of 80,000 bpd.",
    },
    {
        "id": "santos-8", "company": "Santos", "category": "Supply Deals",
        "question": "In June 2026, Santos agreed to supply the South Australian government with how much gas, and over what period?",
        "options": [
            "200 petajoules over 10 years (2030-2040)",
            "100 petajoules over 5 years (2030-2035)",
            "150 petajoules over 8 years (2030-2038)",
            "250 petajoules over 12 years (2030-2042)",
        ],
        "correctIndex": 0,
        "explanation": "Santos agreed to supply the South Australian government 200 petajoules of gas over 10 years (2030-2040).",
    },

    # ---------------- Rio Tinto ----------------
    {
        "id": "rio-1", "company": "RioTinto", "category": "Market Position",
        "question": "What is Rio Tinto's position in the global iron ore market?",
        "options": ["World's largest producer", "Second-largest producer", "Third-largest producer", "Fourth-largest producer"],
        "correctIndex": 0,
        "explanation": "Rio Tinto is the world's largest iron ore producer.",
    },
    {
        "id": "rio-2", "company": "RioTinto", "category": "Commodities",
        "question": "Which of the following is NOT one of Rio Tinto's key commodities?",
        "options": ["Nickel", "Iron ore", "Copper", "Aluminium"],
        "correctIndex": 0,
        "explanation": "Rio Tinto's key commodities are iron ore, copper, aluminium and lithium; nickel is not a core commodity.",
    },
    {
        "id": "rio-3", "company": "RioTinto", "category": "Leadership",
        "question": "Who is the CEO of Rio Tinto?",
        "options": ["Simon Trott", "Peter Cunningham", "Nuno Matos", "Kevin Gallagher"],
        "correctIndex": 0,
        "explanation": "Simon Trott is the CEO of Rio Tinto; Peter Cunningham is the CFO.",
    },
    {
        "id": "rio-4", "company": "RioTinto", "category": "Business Shift",
        "question": "Copper and aluminium now contribute what share of Rio Tinto's profit, overtaking iron ore?",
        "options": ["56%", "44%", "32%", "68%"],
        "correctIndex": 0,
        "explanation": "Copper and aluminium now contribute 56% of Rio Tinto's profit, overtaking iron ore.",
    },
    {
        "id": "rio-5", "company": "RioTinto", "category": "ESG / Energy",
        "question": "Tomago Aluminium — Australia's largest electricity user — received what government support package in August 2026?",
        "options": ["A$2.5 billion", "A$1 billion", "A$1.5 billion", "A$500 million"],
        "correctIndex": 0,
        "explanation": "Tomago Aluminium received a A$2.5 billion government support package to keep the smelter running beyond 2028 and move to 100% renewables from 2033.",
    },
    {
        "id": "rio-6", "company": "RioTinto", "category": "M&A",
        "question": "The Rio Tinto–Glencore merger talks in January 2026 could have created a mining giant worth roughly what?",
        "options": ["$207 billion", "$107 billion", "$157 billion", "$257 billion"],
        "correctIndex": 0,
        "explanation": "January 2026 merger talks with Glencore could have created the world's largest mining company, worth about $207 billion.",
    },
    {
        "id": "rio-7", "company": "RioTinto", "category": "Financials",
        "question": "What was Rio Tinto's 1H 2026 interim dividend per share (its highest in four years)?",
        "options": ["$2.11/share", "$1.11/share", "$3.11/share", "$4.11/share"],
        "correctIndex": 0,
        "explanation": "Rio Tinto declared an interim dividend of $2.11/share, its highest in four years, after underlying earnings rose 43%.",
    },
    {
        "id": "rio-8", "company": "RioTinto", "category": "Global Operations",
        "question": "In May 2026 Rio Tinto began commissioning a low-carbon aluminium expansion in Quebec. What did it cost?",
        "options": ["A$1.5 billion", "A$500 million", "A$1 billion", "A$2 billion"],
        "correctIndex": 0,
        "explanation": "Rio Tinto started commissioning a $1.5 billion low-carbon aluminium expansion in Quebec in May 2026.",
    },

    # ---------------- WiseTech Global ----------------
    {
        "id": "wtc-1", "company": "WiseTech", "category": "Market Position",
        "question": "What is WiseTech Global's position among Australia's listed technology companies by market value?",
        "options": ["Largest", "Second-largest", "Third-largest", "Fourth-largest"],
        "correctIndex": 0,
        "explanation": "WiseTech Global is Australia's largest listed technology company by market value.",
    },
    {
        "id": "wtc-2", "company": "WiseTech", "category": "Flagship Software",
        "question": "WiseTech Global is best known for which software platform?",
        "options": ["CargoWise", "FreightForwarder Pro", "SupplyChain Manager", "LogisticsHub"],
        "correctIndex": 0,
        "explanation": "WiseTech is best known for CargoWise, a global logistics and supply-chain software platform.",
    },
    {
        "id": "wtc-3", "company": "WiseTech", "category": "Leadership",
        "question": "Who is the CEO of WiseTech Global?",
        "options": ["Zubin Appoo", "Richard White", "Jeff Howard", "Raelene Murphy"],
        "correctIndex": 0,
        "explanation": "Zubin Appoo is the CEO of WiseTech Global; Raelene Murphy became Chair in July 2026 and Jeff Howard CFO from Sept 2026.",
    },
    {
        "id": "wtc-4", "company": "WiseTech", "category": "Founder History",
        "question": "Who is the founder of WiseTech Global?",
        "options": ["Richard White", "Zubin Appoo", "Jeff Howard", "Raelene Murphy"],
        "correctIndex": 0,
        "explanation": "Richard White founded WiseTech Global.",
    },
    {
        "id": "wtc-5", "company": "WiseTech", "category": "M&A",
        "question": "For how much did WiseTech Global acquire e2open?",
        "options": ["A$2.1 billion", "A$1.1 billion", "A$1.6 billion", "A$2.6 billion"],
        "correctIndex": 0,
        "explanation": "WiseTech acquired e2open for $2.1 billion (borrowing $2.4 billion), to expand CargoWise beyond freight forwarding into broader supply-chain software.",
    },
    {
        "id": "wtc-6", "company": "WiseTech", "category": "Regulation",
        "question": "In August 2026 the ACCC executed a search warrant on WiseTech. What did the investigation relate to?",
        "options": [
            "Documents concerning the supply of logistics services and software",
            "Allegations of insider trading",
            "Data privacy breaches",
            "Monopolistic pricing practices",
        ],
        "correctIndex": 0,
        "explanation": "The ACCC's August 2026 investigation related to documents concerning the supply of logistics services and software; WiseTech said it would fully cooperate.",
    },
    {
        "id": "wtc-7", "company": "WiseTech", "category": "Restructuring",
        "question": "WiseTech's February 2026 AI restructuring plan aimed to cut roughly how many jobs over two years?",
        "options": ["2,000 jobs", "1,000 jobs", "1,500 jobs", "2,500 jobs"],
        "correctIndex": 0,
        "explanation": "WiseTech announced plans to cut about 2,000 jobs (~29% of its global workforce) over two years to integrate AI — one of Australia's largest AI-related workforce reductions.",
    },
    {
        "id": "wtc-8", "company": "WiseTech", "category": "Governance",
        "question": "What happened after founder Richard White stepped down as executive chair in July 2026?",
        "options": [
            "Media reports emerged regarding alleged personal conduct issues, which he strongly denied",
            "The company announced a major acquisition",
            "A significant share buyback was launched",
            "The company delisted from the ASX",
        ],
        "correctIndex": 0,
        "explanation": "White's July 2026 departure as executive chair followed media reports of alleged personal conduct issues, which he strongly denied.",
    },
]
